// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestWeb
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Tests input with 123
        /// </summary>
        public void Test123()
        {
            #region Variable Declarations
            WinClient uIChromeLegacyWindowClient = this.UIIndexGoogleChromeWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowClient;
            WinControl uIIndexGoogleChromeDocument = this.UIIndexGoogleChromeWindow.UIIndexGoogleChromeDocument;
            WinMenu uIAutofillMenu = this.UIItemWindow.UIItemClient.UIAutofillMenu;
            WinControl uIChromeLegacyWindowDocument = this.UIIndexGoogleChromeWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Chrome Legacy Window' client
            Mouse.Click(uIChromeLegacyWindowClient, new Point(62, 201));

            // Type '1' in 'Index - Google Chrome' document
            Keyboard.SendKeys(uIIndexGoogleChromeDocument, this.Test123Params.UIIndexGoogleChromeDocumentSendKeys, ModifierKeys.None);

            // Type '2' in 'Autofill' popup menu
            Keyboard.SendKeys(uIAutofillMenu, this.Test123Params.UIAutofillMenuSendKeys, ModifierKeys.None);

            // Type '3' in 'Index - Google Chrome' document
            Keyboard.SendKeys(uIIndexGoogleChromeDocument, this.Test123Params.UIIndexGoogleChromeDocumentSendKeys1, ModifierKeys.None);

            // Click 'Chrome Legacy Window' document
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(206, 196));
        }
        
        #region Properties
        public virtual Test123Params Test123Params
        {
            get
            {
                if ((this.mTest123Params == null))
                {
                    this.mTest123Params = new Test123Params();
                }
                return this.mTest123Params;
            }
        }
        
        public UIIndexGoogleChromeWindow UIIndexGoogleChromeWindow
        {
            get
            {
                if ((this.mUIIndexGoogleChromeWindow == null))
                {
                    this.mUIIndexGoogleChromeWindow = new UIIndexGoogleChromeWindow();
                }
                return this.mUIIndexGoogleChromeWindow;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private Test123Params mTest123Params;
        
        private UIIndexGoogleChromeWindow mUIIndexGoogleChromeWindow;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Test123'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class Test123Params
    {
        
        #region Fields
        /// <summary>
        /// Type '1' in 'Index - Google Chrome' document
        /// </summary>
        public string UIIndexGoogleChromeDocumentSendKeys = "1";
        
        /// <summary>
        /// Type '2' in 'Autofill' popup menu
        /// </summary>
        public string UIAutofillMenuSendKeys = "2";
        
        /// <summary>
        /// Type '3' in 'Index - Google Chrome' document
        /// </summary>
        public string UIIndexGoogleChromeDocumentSendKeys1 = "3";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIIndexGoogleChromeWindow : WinWindow
    {
        
        public UIIndexGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Index - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Index - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public WinControl UIIndexGoogleChromeDocument
        {
            get
            {
                if ((this.mUIIndexGoogleChromeDocument == null))
                {
                    this.mUIIndexGoogleChromeDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIIndexGoogleChromeDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIIndexGoogleChromeDocument.WindowTitles.Add("Index - Google Chrome");
                    #endregion
                }
                return this.mUIIndexGoogleChromeDocument;
            }
        }
        
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Index - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private WinControl mUIIndexGoogleChromeDocument;
        
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "193305584";
            this.WindowTitles.Add("Index - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinClient UIChromeLegacyWindowClient
        {
            get
            {
                if ((this.mUIChromeLegacyWindowClient == null))
                {
                    this.mUIChromeLegacyWindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Chrome Legacy Window";
                    this.mUIChromeLegacyWindowClient.WindowTitles.Add("Index - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIChromeLegacyWindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
        }
        
        #region Properties
        public WinMenu UIAutofillMenu
        {
            get
            {
                if ((this.mUIAutofillMenu == null))
                {
                    this.mUIAutofillMenu = new WinMenu(this);
                    #region Search Criteria
                    this.mUIAutofillMenu.SearchProperties[WinMenu.PropertyNames.Name] = "Autofill";
                    #endregion
                }
                return this.mUIAutofillMenu;
            }
        }
        #endregion
        
        #region Fields
        private WinMenu mUIAutofillMenu;
        #endregion
    }
}
